Install ponyc

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -105,7 +105,6 @@ jobs:
       - name: Install cygwin
         run: choco install cygwin
       - name: Install pony-stable
-        shell: powershell
         run: |
           $PSVersionTable.PSVersion
           pwd
@@ -113,7 +112,30 @@ jobs:
           Invoke-WebRequest -Uri $download_url -OutFile pony-stable.zip
           Expand-Archive "pony-stable.zip" -DestinationPath "."
           Rename-Item "pony-stable-0.2.1-66.a85696a-win64" "pony-stable"
+      - name: Install ponyc
+        run: |
+          $req = [System.Net.WebRequest]::Create("https://bintray.com/pony-language/ponyc-win/ponyc/_latestVersion")
+          $req.AllowAutoRedirect = $false
+          $req.Proxy = $null
+          $req.Timeout = 500000
+          $req.UserAgent = 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0)'
+          $res = $req.GetResponse()
+          if ($res.StatusCode -eq "Found")
+          {
+            $latest_url = $res.GetResponseHeader("Location")
+            $latest_ver = $latest_url.Substring($latest_url.LastIndexOf("/") + 1)
+            $latest_ver = $latest_ver.Substring(0, $latest_ver.LastIndexOf("-"))
+            $download_url = "https://bintray.com/pony-language/ponyc-win/download_file?file_path=" + $latest_ver + "-win64.zip"
+            Invoke-WebRequest -Uri $download_url -OutFile ponyc.zip
+            Expand-Archive "ponyc.zip" -DestinationPath "."
+            Rename-Item ($latest_ver + "-win64") "ponyc"
+          }
+          else
+          {
+            Write-Error "Unable to determine latest Pony version from BinTray redirect!"
+            exit 1
+          }
       - name: make
         run: |
-          set PATH=\pony-stable\pony-stable\bin;%PATH%
+          set PATH=\ponyc\ponyc\bin;\pony-stable\pony-stable\bin;%PATH%
           make test
